# Generated by Django 5.2.15 on 2026-08-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
