# Generated by Django 5.2.15 on 2026-08-31 07:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models.get_otp_expiration),
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(default='ALGJuVHAxORLZgMWhhYeNp9fYnA6psE96-GKI7PWhCU', max_length=100),
        ),
    ]
