# Generated by Django 5.2.15 on 2026-08-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otp_active_alter_otp_expires_at_alter_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(default='Vpdi43SlW4Ae35QRPxt0RxeE3js_nqwQJgMr12w84hA', editable=False, max_length=100, unique=True),
        ),
    ]
