# Generated by Django 5.2.15 on 2026-08-31 10:40

import django.utils.timezone
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, editable=False, max_length=100, unique=True),
        ),
    ]
