# Generated by Django 5.2.15 on 2026-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='recipient_phone',
            field=models.CharField(max_length=13),
        ),
    ]
